// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq5E0MDcJs08GSgDKhmi0YGXNrXP4zPBE',
    appId: '1:604337866511:web:e5a640ec6b39a570eae07a',
    messagingSenderId: '604337866511',
    projectId: 'laza-d8f6d',
    authDomain: 'laza-d8f6d.firebaseapp.com',
    storageBucket: 'laza-d8f6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj3VC9u7pwU91u0y83iPmyprfzmaw-6uQ',
    appId: '1:604337866511:android:0c6cb89fd495e2baeae07a',
    messagingSenderId: '604337866511',
    projectId: 'laza-d8f6d',
    storageBucket: 'laza-d8f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlxGTMd4XMAxMRvEWG-JNPEzKIT20aFM',
    appId: '1:604337866511:ios:068f678fc9959ab4eae07a',
    messagingSenderId: '604337866511',
    projectId: 'laza-d8f6d',
    storageBucket: 'laza-d8f6d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlxGTMd4XMAxMRvEWG-JNPEzKIT20aFM',
    appId: '1:604337866511:ios:068f678fc9959ab4eae07a',
    messagingSenderId: '604337866511',
    projectId: 'laza-d8f6d',
    storageBucket: 'laza-d8f6d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq5E0MDcJs08GSgDKhmi0YGXNrXP4zPBE',
    appId: '1:604337866511:web:d7cb27bf1383a23eeae07a',
    messagingSenderId: '604337866511',
    projectId: 'laza-d8f6d',
    authDomain: 'laza-d8f6d.firebaseapp.com',
    storageBucket: 'laza-d8f6d.firebasestorage.app',
  );
}
